'use client'

import Link from "next/link";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Alert } from "@/components/alert";
import { AuthorAvatar } from "@/components/author-avatar";
import { FormField, errorId } from "@/components/form-field";
import { ImagePickerControls } from "@/components/image-picker-controls";
import { AVATAR_BUCKET, AVATAR_SIZES, avatarPath } from "@/lib/avatar";
import { uploadResizedImage, useImagePicker } from "@/lib/upload-image";
import { profileSchema, type ProfileInput } from "./lib/schema";
import { updateProfile } from "./lib/action";

type AccountFormProps = {
    defaultValues: ProfileInput;
    authorId: string;
    avatarUpdatedAt: string | null;
    // Null until first and last name are set (generated by a trigger).
    slug: string | null;
}

export default function AccountForm({defaultValues, authorId, avatarUpdatedAt, slug}: AccountFormProps) {
    const [result, setResult] = useState<{error: string} | {success: true} | null>(null);
    // New picture chosen but not saved yet, shown as a preview.
    const avatar = useImagePicker();
    const {register, handleSubmit, watch, formState: {errors, isSubmitting}} = useForm<ProfileInput>({
        resolver: zodResolver(profileSchema),
        defaultValues,
    });

    const onSubmit = async (values: ProfileInput) => {
        setResult(null);

        if(avatar.file){
            const error = await uploadResizedImage(avatar.file, {
                bucket: AVATAR_BUCKET,
                sizes: AVATAR_SIZES,
                path: size => avatarPath(authorId, size),
                square: true,
            });
            if(error){
                setResult({error});
                return;
            }
        }

        const saved = await updateProfile(values, avatar.change);
        setResult(saved);
        if('success' in saved){
            // The page is revalidated: the stored picture now matches the preview.
            avatar.reset();
        }
    }

    const hasAvatar = Boolean(avatar.file) || (Boolean(avatarUpdatedAt) && !avatar.removed);

    const describe = (name: keyof ProfileInput) => ({
        'aria-invalid': Boolean(errors[name]),
        'aria-describedby': errors[name] ? errorId(name) : undefined,
    });

    return (<form onSubmit={handleSubmit(onSubmit)} noValidate className="flex flex-col gap-6 rounded-xl bg-white/90 p-6 shadow-lg md:p-8">
        <div className="flex flex-col items-center gap-6 sm:flex-row sm:items-start">
            <div className="flex flex-col items-center gap-3">
                <AuthorAvatar
                    size="lg"
                    authorId={authorId}
                    firstName={watch('first_name')}
                    lastName={watch('last_name')}
                    avatarUpdatedAt={avatar.removed ? null : avatarUpdatedAt}
                    previewUrl={avatar.previewUrl}
                />
                <div className="max-w-48">
                    <ImagePickerControls picker={avatar} hasImage={hasAvatar} noun="la photo" addLabel="Ajouter une photo"/>
                </div>
            </div>
            <div className="grid w-full gap-4 sm:grid-cols-2">
                <FormField id="first_name" label="Prénom" error={errors.first_name?.message}>
                    <Input id="first_name" autoComplete="given-name" {...describe('first_name')} {...register('first_name')}/>
                </FormField>
                <FormField id="last_name" label="Nom" error={errors.last_name?.message}>
                    <Input id="last_name" autoComplete="family-name" {...describe('last_name')} {...register('last_name')}/>
                </FormField>
            </div>
        </div>

        <FormField id="description" label="Présentation" error={errors.description?.message} hint="Affichée sur votre page et sur les pages de vos jeux.">
            <Textarea id="description" rows={6} className="min-h-36" placeholder="Parlez de vous, de vos jeux, de ce qui vous inspire…" {...describe('description')} {...register('description')}/>
        </FormField>

        {result && 'error' in result && <Alert>{result.error}</Alert>}
        {result && 'success' in result && (
            <Alert variant="success">
                Profil enregistré.{' '}
                {slug && <Link href={`/authors/${slug}`} className="font-semibold underline">Voir ma page</Link>}
            </Alert>
        )}

        <Button type="submit" size="lg" className="self-end" disabled={isSubmitting}>{isSubmitting ? "Enregistrement…" : "Enregistrer"}</Button>
    </form>)
}
